name: student_mgt
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # core
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.10
  # the annotation package containing @riverpod
  riverpod_annotation: ^2.3.4
  logger: ^2.0.2+1
  sandbox_logger: ^2.1.0
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.2.2

  #firebase
  firebase_auth: ^4.17.0
  firebase_core: ^2.8.0

  # Theme
  flex_color_scheme: ^7.3.1
  flex_seed_scheme: ^1.4.0
  fluttertoast: ^8.2.4
  firebase_ui_auth: ^1.13.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.0
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # a tool for running code generators
  build_runner: ^2.4.8
  # the code generator
  riverpod_generator: ^2.3.11
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.3.9
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.6.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
